name = "INOAssistant"
uuid = "fbbb76bd-cc92-4b2f-9b7e-8d53a46f5940"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
